### ISSUE TITLE
[Suggestion] Structure Overlays Sorting option

### ISSUE THREAD

**Issue by drakray** [mrkite/minutor#350] opened 2022-12-27 03:28 UTC
As the title says, having the option to sort the structure list would be VERY useful, especially in pack with (too) many structures
Searching through the list can be a real pain, at least with alphabetical sorting, structures from a same mod would be easier to find
Also, maybe grouping in folder by modID?, this pictures lists the structures in an Overworld, only(no Nether/other DIMs)
![2022-12-26 22_23_54-](https://user-images.githubusercontent.com/4303126/209606260-dc7800a5-fdce-442e-bc10-cc894483dc57.png)
I might generate its Nether, just to see if the menu will bug out lol

**Comment by EtlamGit** [comment] 2022-12-27 10:43
I understand your problem. Even with vanilla only I sometimes struggle to find the right structure.

What is done now: on Dimension change, the list is cleared. Then for each (new) structure that is found an entry is added to to the bottom of that menu. So the list only contains structures that are currently present in the already loaded world.

At the moment I have no good idea, how to "change" a sorting scheme. So it might be a fixed one.

What could be done:
* add new items at alphabetically correct position
* group mods in own sub folders

I like both ideas.

**Comment by EtlamGit** [comment] 2022-12-27 17:22
Empty the list on World/Dimension both has drawbacks and advantages.
* on world load you are able to select a structure type for highlight and then switch between Dimensions with the selection being preserved
* empty on Dimension change has the advantage of a shorter list

I forgot what the current setting is at the moment. But as both have their reasoning I would not change that and focus on the other topics.

**Comment by drakray** [comment] 2022-12-27 19:25
yeah, no problem with that, I'm just curious to see if I can overflow it XD

**Comment by EtlamGit** [comment] 2022-12-28 06:37
Could you provide a test world containing some structures from mods?

(Alphabetically sorting is working now.)

**Comment by EtlamGit** [comment] 2022-12-28 13:18
Nested menu for each mod should work also.

**Comment by EtlamGit** [comment] 2022-12-28 15:30
> Quick question completely out of the structure subject: can a Definition File have multiple type, like could I make 1 json with blocks, biomes, dimensions AND entities, or must they always have their own file?

No. As the type identifier is on the topmost level of the description. So you need multiple files.

The intended way to bundle multiple files (e.g. into one download) is to place them into a ZIP file.
I have never done that, but the code to handle these "packs" is still there.

**Comment by drakray** [comment] 2022-12-28 15:41
I'll see to make a new world for you, as my working world are HUGE(my current is almost 2Gb)
---
No problem for the multiDef, a zip with 4 file is not really a chore XD

**Comment by EtlamGit** [comment] 2022-12-28 16:19
As the PullRequest is already merged, you can try it on your own -> Actions -> build artifacts

For a test world, ONE region file is sufficient.

**Comment by drakray** [comment] 2022-12-28 16:43
Just tested it, seems to work nicely, although the mod folder themselves are not alphaSorted; having Minecraft Structure on top is weird at first, but understandable and useful
If possible, clicking on the folder could toggle all structures inside, especially useful since clicking on a structure closes the menu

Just saw, toggling structure inside folder does not activate the overlay though

---
[Here is a link](http://www.drakray.com:81/MC/savesNdefs.zip) to a small world with lots of structures
Also in the zip are my modded definition files

**Comment by EtlamGit** [comment] 2022-12-29 11:10
mod menus are sorted now
mod structures work again

**Comment by EtlamGit** [comment] 2022-12-29 11:15
>  If possible, clicking on the folder could toggle all structures inside, especially useful since clicking on a structure closes the menu

Yes, that would be nice.
But Qt QMenu class does not provide functionality to have a sub-menu that is checkable or clickable.

To archive that, we would have to subclass QMenu and implement some own GUI logic.

Maybe you can create a new Issue with only that topic, Then we have a reference for implementing it later.

**Comment by EtlamGit** [comment] 2022-12-29 13:11
Is it possible to provide a test region file that is created (and last used) with a very old Minecraft version?
(before "The Flattening" meaning version below 1.12) The older the better!

**Comment by drakray** [comment] 2022-12-30 22:46
2 saves, Release Version 1.0 and 1.3.1
[saves.zip](https://github.com/mrkite/minutor/files/10326465/saves.zip)
Not very explored though, just generated

**Comment by EtlamGit** [comment] 2022-12-31 10:20
Do these contain modded features?

Sorry, didn't explain that I want to test modded structures for older versions . . .
But nevertheless, I didn't played that old versions, so they contain plenty of valuable data to debug.
(Especially, as version 1.0 does not render at all.)

Another remark: I have downloaded both files now. In case you want to take them down from the wild and public internet for privacy reasons, it is possible now.

**Comment by drakray** [comment] 2022-12-31 15:32
There was a change in the saved files format in 1.2.1, probably the reason why it doesn't work
No, those are vanilla saves, I don't know how far I can go to add modded feature, Forge was not always around XD

**Comment by EtlamGit** [comment] 2023-01-02 17:28
I found a "simple" way to toggle some of the Overlays:
* click on [Structure Overlays] will toggle all vanilla Structure Overlays
* click on [Entity Overlays] will toggle all Entity Overlays

It will toggle visibility, not enable/disable. This feels a bit strange at the moment. Especially when you toggle all to ON and then move the map and find new structures, these are not enabled.

**Comment by Kolcha** [comment] 2023-01-03 23:31
> But Qt QMenu class does not provide functionality to have a sub-menu that is checkable or clickable.

this is expected behavior - sub-menu should be expanded on click because "auto-expand" on hover can be disabled (at least in Linux environments).

what about adding the first checkable item (as any other items in menu) called something like "enable all" (and checked by default) in sub-menu which will switch all other items to the same state it has. it easy to achieve - just connect `triggered()` (not `toggled()` - we are interested in only user-triggered events) signal from it to `setChecked()` slot of other items. logic behind "structures" `QAction`s should react on `toggled()` signal instead (programmatically changed state also should affect view/rendering results). I don't know how it is implemented now.

also it would be nice to have tri-state checkbox on this item, but unfortunately `QAction` supports only "classic" checkbox. this can be achieved by using `QWidgetAction` with embedded `QCheckBox` (which can be tri-state), but this is a bit complicated and definitely requires some logic to display this "third state" when not all items in menu are in the same state and to update it correctly when any of items changes own state.

I can look into this at weekend, this is interesting feature to implement for me.

**Comment by EtlamGit** [comment] 2023-01-04 18:11
The LabeldSeparator is already a self-made combination of a separator line and a text label.
It would be possible to add a tri-state checkbox there:
![grafik](https://user-images.githubusercontent.com/5821779/210621286-4e6ce269-09af-436e-a951-056242bbc075.png)

I have (not checked in) code that uses that LabeldSeparator for the vanilla structures and entities.
Do you want me to check in this experimental code?

Adding a toggle/enable/disable separator for EACH mod sub-menu might be too much. For the provided test world there are several mob sub-menus with only 1 or 2 structure entries in them. So the rate of toggle action versus real actions could be quite strange.  We may have to test the approach and look how it feels. At least I have no other idea how to handle this easily (without another self made class).

What I had in mind is a combination of a tri-state checkbox with the sub-menu we already have:
![grafik](https://user-images.githubusercontent.com/5821779/210619886-e541bb15-e09d-4abd-b806-57e307ed2b0e.png)
When clicking on the text, the sub-menu is opened, when clicking the checkbox, the state is altered.
But I have also other ideas for that unused space in front of the sub-menu. Not sure which I like more at the moment...

**Comment by EtlamGit** [comment] 2023-01-04 18:17
Here is an example how the approach with label for each sub-menu would look like:
![grafik](https://user-images.githubusercontent.com/5821779/210622394-35580898-325b-4413-8a66-f998f6d74f60.png)

**Comment by drakray** [comment] 2023-01-04 18:23
I like the "toggle all" header more, and it would make even more sense by putting all minecraft:* structure in their own submenu too, I think
this way we could even skip the modName part of the structure in the subMenu, would make for more readability and reduce width

**Comment by EtlamGit** [comment] 2023-01-04 19:39
I just moved vanilla structures out of a sub-menu to reduce clicking some month ago . . . so they should stay in first menu level.

Reducing names by redundant part is a good point.

**Comment by drakray** [comment] 2023-01-04 19:52
yeah no problem I understand that XD
I personally have no problem with more clicking, if it means cleaner UI 😉

**Comment by Kolcha** [comment] 2023-01-04 23:00
> I just moved vanilla structures out of a sub-menu to reduce clicking some month ago . . . so they should stay in first menu level.

just an idea: no mods - items are in the first level menu, have mods - vanilla structures also in sub-menu. but may be tricky to implement...

**Comment by EtlamGit** [comment] 2023-01-07 11:06
Hi @Kolcha , I have checked in my intermediate state here:
https://github.com/EtlamGit/minutor/tree/test-menu-structures

You can take a look there when you like.
* checkbox is added, but unused and without any functionality (even invisible as default)
* toggle works for vanilla but not for mods
* "toggle all" label is created in each mod sub-menu but not used up to now

**Comment by Kolcha** [comment] 2023-01-10 12:38
Hi @EtlamGit , I looked into your sources. I can say it is a good start (it even has some placeholders in code for future logic), but personally I don't like "checkbox + separator" item design, it looks very strange... as for me, it is better to use just regular checkbox + standard separator item below it. the only thing I can say, it will be tricky to implement...

**Closed** 2023-04-08 14:41 UTC
Labels: enhancement
