### ISSUE TITLE
Doesn't work on 1.11.2 worlds

### ISSUE THREAD

**Issue by polkovnikov-ph** [mrkite/minutor#108] opened 2017-01-12 11:08 UTC
Opening world file leads to a gray screen with "unknown biome" everywhere.

**Comment by BigAlanM** [comment] 2017-01-18 12:20
I've  run the latest release of Minutor on a PCMCv1.11.2 world with absolutely NO problems.

**Comment by TeriXeri** [comment] 2017-01-27 01:06
Running the last Release version (2.1) I get the world to show fine, but entities dont show up at all.

If I update the definitions the world turns weird and grey in parts, and entities still dont show up.

Any chance there will be a downloadable updated version that works on 1.11 blocks/entities etc.

**Comment by EtlamGit** [comment] 2017-01-27 19:14
With 1.11 Mojang completely changed the names of entities. Necessary changes to the definition files where done in a way that older versions still work without crashing, but for sure can not support the new style. So "no Entities" is expected.
Gray Grass and Leaves is caused by the Biome dependent coloring made during Christmas. Just use a definition file version from the history: before Christmas and after the 1.11 update. Then everything should look fine.
As far as I know, only the Mac version is missing for a new release. But I don't have one to help there...

**Comment by EtlamGit** [comment] 2017-03-05 14:26
I'm not able to reproduce your description and nobody else either.
@polkovnikov-ph is this problem still valid?
Otherwise I will close this issue in the next days.

**Comment by ceving** [comment] 2017-05-03 11:55
I tried this map: http://mcpedl.com/ekzas-terrain-overhaul/
and got the same error: gray window with "Unknown Biome".
But I am using an older version (1.6.3_amd64) because the newer does not work on Ubuntu 14.04.

**Comment by ceving** [comment] 2017-05-03 12:10
Now I tried 2.1 on Windows and got the same effect. I also tried to import the ultimate pack, but it does not make any difference.

On Windows I tried superflat map an Imperial City: http://mcpedl.com/imperial-city/

I never see anything but "Unknown Biome".

**Comment by EtlamGit** [comment] 2017-05-03 19:11
Are all these worlds Windows 10 (Minecraft PE) save versions?
This format is not supported, please use the vanilla PC format.

**Comment by matvnefedov** [comment] 2017-05-26 20:21
> Are all these worlds Windows 10 (Minecraft PE) save versions? This format is not supported, please use the vanilla PC format.
I have the same problem. After re-install Windows 7, none of the versions of the program is not working. Show only grey and black squares.

May be need to install some specific drivers, libs or ect?

**Comment by EtlamGit** [comment] 2017-05-27 09:23
Again: Do you use "Vanilla Minecraft (PC version)" / or / "Minecraft Windows 10 version (PE = Pocket Edition)"
Please provide the exact version and version number of your Minecraft and the worlds.

Please provide the exact version number of your Minutor.
Please provide the version of definition files your Minutor is using:
 C:\Users\<yourname>\AppData\Local\seancode\Minutor\*.json

You could also check in the registry if these definition packs are enabled:
 HKEY_CURRENT_USER\Software\seancode\Minutor

Also please provide an affected world (e.g. zipped save folder).

We can only debug this problem if we can reproduce it.

**Comment by matvnefedov** [comment] 2017-05-27 14:24
EtlamGit,
Mineraft version: PC version, 1.11.2, Vanilla, License 
Minutor version: 2.1 or earlier
seancode: 1416636158
From registry: 1416636158.json
[TestWorld.zip](https://github.com/mrkite/minutor/files/1033573/TestWorld.zip)
The problem is not in the world. The world is displayed successfully on another PC with Win 7.
May be you can try to check on the fresh windows (use virtual machine)?

Win 7 x64 with all the latest actual updates.

**Comment by BigAlanM** [comment] 2017-05-27 14:54
I've had no problems running Minutor 2.1.0 on Windows 10 operating system and have viewed worlds on all version up through PCMC v 1.12 preview snapshot.
One thing, if you downloaded 2.1 last year I suggest that you goto the definitions section,
https://github.com/mrkite/minutor/tree/master/definitions
and dowload and install any new files.
These get updated periodically without any mention of a version change to Minutor and/or update to download executable.

**Comment by EtlamGit** [comment] 2017-05-27 15:56
The version number for each definition file can be found inside, or via the definition management dialog:
![clipboard01](https://cloud.githubusercontent.com/assets/5821779/26522625/a225c20e-4304-11e7-82ee-29f06637cbec.jpg)
As you can see, your TestWorld can be displayed correctly.

You do not need any drivers or prerequisites for Minutor!
It is self-containing everything it needs. Only definition updates do not work properly at the moment.

But you can exchange the definition files content yourself here from GitHub:
https://github.com/mrkite/minutor/tree/master/definitions

**Comment by matvnefedov** [comment] 2017-05-27 15:58
Hm... I have only entity type.

**Comment by matvnefedov** [comment] 2017-05-27 16:41
How add Definitions?
![default](https://cloud.githubusercontent.com/assets/4114576/26522964/825213aa-4314-11e7-823c-0ac6155932f9.png)

**Comment by EtlamGit** [comment] 2017-05-27 18:57
- download latest Minutor release from this page
- delete folder C:\Users\<yourname>\AppData\Local\seancode\Minutor
- delete registry key HKEY_CURRENT_USER\Software\seancode\Minutor\packs
- delete registry key HKEY_CURRENT_USER\Software\seancode\Minutor\packupdate
- start Minutor (this will regenerate definition files)

Caution! Editing in the Windows registry can destroy your Windows installation!
If you never did that in the past or feel uncomfortable with it, ask for assistance.

Afterwards you could exchange the content of the 4 files with the 4 .json files I mentioned earlier.

(I will take a look into default definition file handling and may add a recovery button...)

**Comment by matvnefedov** [comment] 2017-05-27 19:13
EtlamGit 
Thank you.
Now Minutor is working correctly

**Comment by EtlamGit** [comment] 2017-05-27 20:12
Great to hear!
@polkovnikov-ph @ceving could you please check if you also have problems with missing definition files?

**Comment by polkovnikov-ph** [comment] 2017-05-28 08:16
> download latest Minutor release from this page

Which page? I open http://seancode.com/minutor/, use "Windows, No installer".

![image](https://cloud.githubusercontent.com/assets/2983969/26527164/40c82c30-437d-11e7-9471-4b89a4b8ef36.png)

As binary wasn't built with debug information, I have no idea what happened.

**Comment by EtlamGit** [comment] 2017-05-28 09:25
The download page you mentioned should contain the same file like here on GitHub (which I was referring to).

Did you remove any faulty definition files like described above?

When does Minutor crash? Directly when starting or when opening a world?

I get this crashes occasionally when I open a running world that is saving to the disk at that moment or crashed during doing that. And some time ago with an older version when the definition files are corrupted.

**Comment by polkovnikov-ph** [comment] 2017-05-28 13:15
> Did you remove any faulty definition files like described above?

Yes, and registry keys too.

> When does Minutor crash? Directly when starting or when opening a world?

Immediately at startup.

> I get this crashes occasionally

It crashes stable.

**Comment by EtlamGit** [comment] 2017-05-28 15:02
The latest Minutor is 64bit, do you have 64bit Windows or still 32bit?

Another thing that you can try is:
- delete everything as described above again (and before each try)
- start Minutor from a command shell, maybe there is some useful output on the console log
- check the content of the definition files after a crash (look at the end of the file)

**Comment by polkovnikov-ph** [comment] 2017-05-28 16:44
@EtlamGit I found the problem. I've been running it straight from 7zip. Works fast and flawless.

Nevertheless, please, enable debug symbols and make a separate download for them. Cases when C++ crashes in production are not rare, and it's hard to do anything when you don't know where the crash happened.

**Comment by mrkite** [comment] 2017-05-28 20:31
I don't think that's necessary.  It's open source, if you're in a position that debug symbols would help you, you're also in a position to compile it yourself in debug mode.

**Comment by polkovnikov-ph** [comment] 2017-05-28 22:55
Not really. If it requires the user to download a gigabyte of bloatware framework and waste an hour on figuring out installation process, it really makes sense for a developer to publish debug symbols.

**Closed** 2017-10-06 15:31 UTC
